Appendix D Update
oasis-tcs/openc2-oc2ls pull request #415
Opened 2023-06-08 15:04 UTC by dlemire60

Per issue #414, there are terminology misalignments between the LS Appendix D and the recently published JADN-IM CN.  This PR adds the CN as an LS reference, and updates the content of Appendix D to incorporate the reference and align the terminology.

2023-11-27 15:29 UTC, davaya requested changes
I approve of the changes.

There's a typo in "usuall", but I think the sentence could be simplified from

> where each definition may be basic (e.g., using a single, usuall "primitive" type) or structured (e.g., using a "compound" type). 

to: 
> where each type may be simple (primitive) or structured (compound).

2023-11-27 21:52 UTC, dlemire60 commented
Wording tweaked per @davaya's comment.

2023-11-28 01:50 UTC, davaya approved these changes

2023-11-29 21:21 UTC, dlemire60 commented
Approved for merging at the 29 Nov '23 working meeting.

2023-11-29 21:21 UTC, merged